Fix set murdered
Impostor/Impostor pull request #192
Opened 2020-11-25 10:02 UTC by ZiadMontaser

### Description
Fix set murdered
<!--

2020-11-25 10:05 UTC, js6pak commented
Wouldn't this break game state, anticheat would think that player is still alive? And this really should be done other way around + with dead/impostor checks

2020-11-25 10:50 UTC, ZiadMontaser commented
are we good now

2020-11-30 13:12 UTC, AlexejheroYTB requested changes

2020-11-30 13:12 UTC, AlexejheroYTB commented on src/Impostor.Api/Net/Inner/Objects/IInnerPlayerControl.cs
>          ValueTask SetMurderedAsync();
Remove `SetMurderedAsync`

2020-11-30 13:12 UTC, AlexejheroYTB commented on src/Impostor.Server/Net/Inner/Objects/InnerPlayerControl.Api.cs
> +            var impostorNetId = impostor.Character.NetId;
Check if the `impostor` is actually an impostor, check if they're not dead, and also check if the target player is not dead.

2020-11-30 13:26 UTC, AlexejheroYTB commented
Edit the description of the PR to include `closes #183`

2020-11-30 19:41 UTC, merged