Add IInnerPlayerControler#SetExiledAsync
Impostor/Impostor pull request #271
Opened 2021-01-06 19:49 UTC by Minorusama

### Description
Adds a `SetExiledAsync` to `IInnerPlayerControler`. It allows to kill a player with no animation and doesn't leave a body to report.

2021-01-07 01:40 UTC, asqapro commented
I made a similar function [here](https://github.com/asqapro/Impostor/commit/c672fa9a6450dfa39d0e920d76674598f8fde4a6), but yours is cleaner. I can confirm the functionality works very well, I've been testing it for a week or so. As soon as the function is called, the player disappears with no body and turns into a ghost. Some visual tasks will still show up, like garbage chute on The Skeld, but that's normal ghost behaviour according to the wiki. 

I hope this PR gets merged quick, `SetMurderedByAsync` drove me crazy because it teleports the impostor who did it.

2021-03-14 22:51 UTC, js6pak requested changes

2021-03-14 22:51 UTC, js6pak commented on src/Impostor.Api/Net/Inner/Objects/IInnerPlayerControl.cs
> +        ValueTask SetExiledAsync();
SetExiledAsync -> ExileAsync

2021-03-14 22:51 UTC, js6pak commented on src/Impostor.Server/Net/Inner/Objects/InnerPlayerControl.Api.cs
> +                return;
throw a `ImpostorProtocolException` like in `MurderPlayerAsync`

2021-03-15 18:49 UTC, js6pak commented
Seems like the commit history is completely broken now? You can just soft reset to master

2021-03-23 20:12 UTC, js6pak approved these changes

2021-03-23 20:12 UTC, merged