Allow Android Versions
Impostor/Impostor pull request #375
Opened 2021-04-04 03:17 UTC by JohnTranQUT

### Description

Allow android phones onto airship impostor server

2021-04-04 07:44 UTC, js6pak commented
If forte decided to change the protocol version, are you sure it will work?

2021-04-04 07:57 UTC, JohnTranQUT commented
> If forte decided to change the protocol version, are you sure it will work?

I had not done anything to the protocol however I tested a few games with andriod/bluestacks and it appears to be running smoothly with the https://github.com/Impostor/Impostor/pull/372 .

I will report back as soon there are any concerns.

2021-04-05 20:52 UTC, js6pak requested changes

2021-04-05 20:52 UTC, js6pak commented on src/Impostor.Server/Net/Manager/ClientManager.cs
> +            GameVersion.GetVersion(2021, 4, 2), // 2021.4.2a andriod
```suggestion
            GameVersion.GetVersion(2021, 4, 2), // 2021.4.2a
```

2021-04-06 02:45 UTC, JohnTranQUT commented on src/Impostor.Server/Net/Manager/ClientManager.cs
> +            GameVersion.GetVersion(2021, 4, 2), // 2021.4.2a andriod
Yep, spelt it wrong. My bad.

2021-04-06 18:50 UTC, js6pak approved these changes

2021-04-06 18:50 UTC, merged