Airship
Impostor/Impostor pull request #377
Opened 2021-04-06 19:19 UTC by js6pak

2021-04-06 21:16 UTC, IrishBruse commented
Aren't publics on interface methods redundant?

2021-04-09 21:08 UTC, miniduikboot requested changes
This branch has gotten a bit too large, making it hard and not fun to review.

Most of my critique concerns the vent api, which is something that imo should not have been in this PR as it is not really airship related

Removing the reactor stuff was also something that was bound to happen in future, but the timing is rather unfortunate as the replacement is not ready yet.

I think that in future we should aim to keep these update branches smaller and do non-essential refactorings afterwards.

2021-04-09 21:20 UTC, js6pak commented on src/Impostor.Api/Events/Game/Player/IPlayerVentEvent.cs
> +        public Vent Vent { get; }
I should've added comment to that event, but:
- IPlayerVentEvent: called when player vents (SnapTos) to another vent
- IPlayerEnterVentEvent/IPlayerExitVentEvent: called when player enters/exits a vent

2021-04-09 21:21 UTC, js6pak commented on src/Impostor.Api/Innersloth/Customization/ColorType.cs
> +    public enum ColorType
To reflect airship client changes, it was changed from byte to int there aswell

2021-04-09 21:24 UTC, js6pak commented on src/Impostor.Api/Innersloth/Maps/AirshipData.cs
> +            ConnectVents(AirshipVent.Ids.CargoBay, left: AirshipVent.Ids.Showers, right: AirshipVent.Ids.Records);
I can't really think of any better way, but it definitely shouldn't be editing ReadOnlyDictionary, you are right on that

2021-04-09 21:24 UTC, js6pak commented on src/Impostor.Api/Innersloth/Platforms.cs
> +    public enum Platforms
wdym?

2021-04-09 21:25 UTC, js6pak commented on src/Impostor.Server/Net/Inner/Objects/Components/InnerPlayerPhysics.cs
> +                            await _eventManager.CallAsync(new PlayerExitVentEvent(Game, sender, _playerControl, vent));
https://github.com/Impostor/Impostor/pull/377#discussion_r610910629
https://github.com/Impostor/Impostor/pull/377/files#diff-29d84eef1afe966f93dec1a9ebc0f21ce87727e8152397dbdafd8f2f58f1db28R131

2021-04-09 21:31 UTC, miniduikboot commented on src/Impostor.Api/Events/Game/Player/IPlayerVentEvent.cs
> +        public Vent Vent { get; }
Ah, didn't get that distinction. Maybe it'd me more clear to rename IPlayerVentEvent to IPlayerMoveEvent?

Adding comments to the would be much appreciated, but that's maybe out of scope for this PR

2021-04-09 21:32 UTC, miniduikboot commented on src/Impostor.Api/Innersloth/Maps/AirshipData.cs
> +            ConnectVents(AirshipVent.Ids.CargoBay, left: AirshipVent.Ids.Showers, right: AirshipVent.Ids.Records);
Would it be possible to add the left/right/center optional arguments to the class constructors?

2021-04-09 21:33 UTC, miniduikboot commented on src/Impostor.Api/Innersloth/Platforms.cs
> +    public enum Platforms
```
Unknown = 0
StandaloneEpicPc = 1,
// etc
```

2021-04-09 21:47 UTC, miniduikboot commented on src/Impostor.Server/Net/Inner/Objects/Components/InnerPlayerPhysics.cs
> +                            await _eventManager.CallAsync(new PlayerExitVentEvent(Game, sender, _playerControl, vent));
disregard this, I missed the different purpose of playerventevent

2021-04-11 12:04 UTC, merged