Using MapData for Tasks
Impostor/Impostor pull request #395
Opened 2021-04-18 14:39 UTC by Minorusama

### Description
Rework of #275, marked as draft as I didn't have the time to test it yet.

- Adds a method to complete a task in TaskInfo
- Adds a method to complete all tasks in InnerPlayerControl
- Adds a refence to ITask in TaskInfo to identify the task

### Closes issues

- closes #261
- closes #202

2021-04-19 10:25 UTC, JohnTranQUT commented
@Minorusama I've tested and found that the tasks for AirShip was off.
I've made the fixes and left in https://github.com/Minorusama/Impostor/pull/4 pull for you to update.

- [x] Also gotten rid of a warning
- [x] Add in an example event-listener.
- [ ] Other maps tasks tested thoroughly (if innersloth changed anything).

2021-04-26 14:16 UTC, js6pak requested changes

2021-05-12 14:40 UTC, miniduikboot commented on src/Impostor.Api/Net/Inner/Objects/IInnerPlayerControl.cs
> +        ValueTask CompleteAllTasksAsync();
Agree, I don't think this method belongs in the public API

2021-05-12 14:47 UTC, miniduikboot commented on src/Impostor.Plugins.Example/Handlers/PlayerEventListener.cs
> +                await e.PlayerControl.CompleteAllTasksAsync();
just inline CompleteAllTasksAsync here and remove it from the public api

2021-05-12 14:55 UTC, miniduikboot commented on src/Impostor.Server/Net/Inner/Objects/InnerGameData.TaskInfo.Api.cs
> +                    return;
do we want to throw an exception when api users try to complete an already completed tasks? The method not doing anything when it is already completed would surprise me

2021-05-12 15:42 UTC, miniduikboot commented on src/Impostor.Server/Net/Inner/Objects/InnerPlayerInfo.cs
> +        public void Deserialize(IMessageReader reader, IEventManager eventManager, Game game)
what are these new arguments used for?

2021-05-12 17:10 UTC, js6pak approved these changes

2021-05-12 17:12 UTC, miniduikboot approved these changes

2021-06-10 18:54 UTC, merged