Implement event to detect game option changes
Impostor/Impostor pull request #552
Opened 2023-11-26 22:24 UTC by miniduikboot

### Description

This can be triggered by both RPC 02 and a(nother) plugin calling SyncSettings to force certain settings on the host. Users of this API could cause this event to recurse by calling SyncSettingsAsync inside an event handler, so we prevent such reasonable foreseeable misuse.

2023-11-26 23:21 UTC, js6pak requested changes

2023-11-28 22:07 UTC, miniduikboot commented on src/Impostor.Server/Net/Inner/Objects/InnerPlayerControl.cs
> +                        Api.Events.IGameOptionsChangedEvent.ChangeReason.Rpc));
Looks like Rpc02SyncSettings got deprecated a while ago, I guess we stop handling that RPC as well

2023-12-03 21:31 UTC, js6pak commented on src/Impostor.Server/Net/Inner/Objects/GameManager/Logic/LogicOptions.cs
> +            Api.Events.IGameOptionsChangedEvent.ChangeReason.Rpc));
```suggestion
        await _eventManager.CallAsync(new GameOptionsChangedEvent(
            _game,
            Api.Events.IGameOptionsChangedEvent.ChangeReason.Rpc)
        );
```

2023-12-03 21:38 UTC, miniduikboot commented on src/Impostor.Api/Events/Game/IGameOptionsChangedEvent.cs
> +            Rpc,
It's a deserialization, but the source here would be best described as "Host"

This is exposed to let plugins detect if they are triggering on their own changes

2024-01-25 00:03 UTC, js6pak approved these changes

2024-01-25 11:14 UTC, merged