Bugfix/fix set name
Impostor/Impostor pull request #652
Opened 2024-09-28 15:40 UTC by danbudworthmead

### Description

Fixes not being able to set the name of a player via impostor. 
The switch statement in the client now expects a uint32 of which should be the players netId from how the client has SetNameRpc.

![image](https://github.com/user-attachments/assets/8c558b94-b05e-46ee-8346-98133cfa151a)
![image](https://github.com/user-attachments/assets/c796bfb5-3178-41ce-85b5-67c525d561e0)

2024-09-28 15:49 UTC, NikoCat233 approved these changes

2024-09-28 15:50 UTC, NikoCat233 commented
Can you reopen a pr that based on newest github commit and write a clear commit message?

2024-09-28 15:50 UTC, NikoCat233 requested changes
Can you reopen a pr that based on newest github commit and write a clear commit message?

2024-09-28 16:48 UTC, danbudworthmead commented
> Can you reopen a pr that based on newest github commit and write a clear commit message?

hope that commit message is more clear :)

2024-09-29 21:19 UTC, miniduikboot approved these changes

2024-10-05 10:28 UTC, merged