Record and restore player colors
Impostor/Impostor pull request #659
Opened 2024-11-17 21:10 UTC by miniduikboot

### Description

This prevents situations where a player that requested red has a different color when rejoining because red is the default color of a PlayerInfo object. This is most noticeable if the host is late with rejoining, and a lot of players are alreading in WaitingForHost limbo.

When the host finally rejoins, they will not assign Red immediately to players that requested Red as it is "in use", and instead assign the next color.

By recording and restoring this is avoided, and players tend to get their own colors back in most cases.

This is not something that officials do at the moment, but I don't think this has an impact on mods, as a normal checkcolor/setcolor cycle will take place as usual.

2024-12-23 01:02 UTC, js6pak requested changes

2025-01-04 20:17 UTC, miniduikboot commented on src/Impostor.Server/Net/Inner/Objects/InnerPlayerControl.cs
> +                _logger.LogWarning("Tried to record color, but couldn't get player with id {PlayerId}", OwnerId);
I removed the Game.IsHostAuthoritive check from here entirely, the value isn't restored anyway in HostAuthoritive mode, so it is a dead store in HA mode (Game.Data.cs:483)

2025-01-12 18:18 UTC, js6pak approved these changes

2025-01-26 16:38 UTC, miniduikboot commented
Needs rework, when the host disconnects the `Tried to record color, but couldn't get player with id X` message is thrown sometimes a second later. Occurs ~100 times a day, so not acceptable to upstream for now

2025-05-22 21:48 UTC, miniduikboot commented
Rework can be performed later

2025-05-22 21:48 UTC, merged